name: deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "**.edn"
      - "**.css"
      - "**.js"
      - "**.clj"
      - "**.yml"
      - "**.toml"
      - "**.json"
      - "Dockerfile"
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup deploy environment
        uses: superfly/flyctl-actions/setup-flyctl@master
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to fly.io docker registry
        run: flyctl auth docker
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: "registry.fly.io/bljog:${{ github.sha }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Deploy
        run: flyctl deploy --app luciano-laratelli --image "registry.fly.io/bljog:${{ github.sha }}"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
